### ISSUE TITLE
Improve Sharing

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#117]
- [x] It should redirect to camera live view instead of camera list when user press back button in sharing page
- [x] Show a confirm dialog before removing share / revoking share request
- [ ] Resend button?

**Comment by liutingdu** [comment]
Resend share request - confirmed with @azharmalik3, there is no API for this.

@marcoherbst Is it essential on mobile? I don't have a good idea on the UI yet..

**Comment by marcoherbst** [comment]
It's not essential, leave it out. 
API endpoint requested: https://github.com/evercam/evercam-api/issues/496
