### ISSUE TITLE
intercom conversation page does not have instant messages

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-play-android#137]
@liutingdu 

while conversing on intercom I and faisal found that the conversation page does not have instant messaging.i would have to close the conversation and open it again for the new messages to appear.

**Comment by liutingdu** [comment]
Hi @muneeb2542 , 

Thanks for reporting this. But it is working for me, could you please provide detailed steps so I can reproduce it? You can reach me on Skype if it helps :)

**Comment by muneeb2542** [comment]
@liutingdu 

i was trying to add a new camera through "Scan for cameras" and then i clicked "show other devices".After that i clicked on "this is a camera" for my camera and wrote the name of the camera and clicked on report.
Then a conversation page was open and since then i am conversing and not receiving instant messages.I would have to close it first and open it again to see the new messages.

**Comment by liutingdu** [comment]
Are you talking about this page? It's showing the conversation list and when I get a reply, it shows a blue dot that indicates new message coming. Does it behave differently on your side?

![screenshot_20151222-114940](https://cloud.githubusercontent.com/assets/5046761/11954701/6d56deda-a8a2-11e5-9c89-a206c27b898c.png)

**Comment by muneeb2542** [comment]
No,this screen behaves fine.The main issue comes when i click on it and the new page opens.Right now it is working fine but an hour ago i was not receiving massages instantly.I had to go back one step and open again to see new messages.

**Comment by liutingdu** [comment]
I guess that's a temporary issue with Intercom server, and I am not sure what we can do about it.  I'll keep an eye on this and please let me know if it's happening again and reproducible. Thanks for noticing problems like this and report it :)
