### ISSUE TITLE
 Re-enable the Analytics reports

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#14]
After implementing the callbacks, re-enable the Analytics reports, , in the VLC version it measures the stream loading speed and successful/failed and send the event analytics report to Logentries, Google Analytics and Keen.io.

**Comment by GNUDimarik** [comment]
I'll add connection speed read API for java, is this acceptable?

**Comment by liutingdu** [comment]
Connection speed? Do you mean the bit rate?

**Comment by GNUDimarik** [comment]
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-rtspsrc.html#GstRTSPSrc--connection-speed
