### ISSUE TITLE
Unable to play video and it didn't switch to JPG view

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#155]
This is happening for camera ```mobile-mast```

It's loading video view forever and ExoPlayer onError() never gets called

**Comment by liutingdu** [comment]
https://github.com/google/ExoPlayer/issues/1356

**Comment by marcoherbst** [comment]
My reading of the Exoplayer ticket is that we must add validation checks on Evercam Media. @mosic if you agree then that sounds like a new issue for media? Nice one @liutingdu

**Comment by liutingdu** [comment]
Closing this because it's a media issue now
