### ISSUE TITLE
Camera thumbnail image is very old

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#156]
Dashboard has the same issue, it will involve discussion with @mosic

**Comment by mosic** [comment]
@liutingdu On last Friday I made evercam-media update the thumbnail in the background after it has been requested, so now you can just request it again with the same url and it will return a newer image.

**Comment by liutingdu** [comment]
@mosic Now the app works same way with dashboard, thumbnail image is updated every time when user hit refresh button. Thanks for the nice server side work :)
