### ISSUE TITLE
Use dash.evercam.io instead of dashboard.evercam.io for recording widget

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-play-android#167]
`RecordingWebView` still references the old dashboard domain, it should use dash.evercam.io: [RecordingWebView.java#L52](https://github.com/evercam/evercam-play-android/blob/5b8ea7ee30fb352e888ff5754b29b531a5a3123a/evercamPlay/src/main/java/io/evercam/androidapp/recordings/RecordingWebView.java#L52)

Btw this is the problem that is stopping the recording view from loading in the app, as the dashboard cert expired yesterday.

**Comment by liutingdu** [comment]
@mosic Thanks for finding the issue! I'll get it deployed tomorrow :)
