### ISSUE TITLE
Travis build failed

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#17]
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':evercamPlay'.
> failed to find target android-22 : /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

**Comment by SandroMachado** [comment]
Fixed with the PR #36
