### ISSUE TITLE
Gstreamer live view doesn't work with landscape

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#2]
Currently if the screen rotates, the video surface is always resizing incorrectly, instead it should works the same way with the VLC version

**Comment by liutingdu** [comment]
### Dmitry said:

Currently if the screen rotates, the video surface is always resizing incorrectly, instead it should works the same way with the VLC version.

This is the reason why I suggest to use Gstreamer tutorial, it works there and Liuting will be able to customize UI.

**Comment by liutingdu** [comment]
@GNUDimarik

Do you think the rtspviewer code will work with the landscape fullscreen?
I tried their app but in landscape it's showing two cameras, so couldn't test this.

**Comment by GNUDimarik** [comment]
@liutingdu 
Please describe this feature, may be I got it wrong ...
Please provide detailed description here and I'll be able to tell you what should we do

**Comment by liutingdu** [comment]
@GNUDimarik 

See the screenshot for [portrait](https://drive.google.com/file/d/0B5FrFyWSBkhLdzIwX0F0bENkNTA/view?usp=sharing) and [landscape](https://drive.google.com/file/d/0B5FrFyWSBkhLc0hNT0gtU0F4Rk0/view?usp=sharing)

The stream on rotated phone is not full screen and it should be, is it something that can be fixed?

**Comment by liutingdu** [comment]
It was caused by some remaining VLC code, should be fixed now.
