### ISSUE TITLE
Video is not smooth under bad network condition

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#28]
Except use lower resolution stream (which need change on the cameras), is there any other ways to improve this? Buffering?

**Comment by GNUDimarik** [comment]
I think buffering will require a lot of time for filling buffer. I can disable sync by time for video sync and it will show frame exactly when it receives it. But we can try to fill buffer gradually increase it's size, it may work, but I don't think so it give us really smooth video. Actually we can't show smooth video NETWORK stream when NETWORK is down

**Comment by liutingdu** [comment]
@GNUDimarik  For low bandwidth conditions, if the video can get any smoother by dynamically increasing buffering size, I think it's worth to try!
