### ISSUE TITLE
Gstreamer: Take snapshot from video

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#3]
The user can take snapshot and save it locally in VLC version for both JPG view and video view. But in GStreamer version, currently it only works for JPG view.

**Comment by liutingdu** [comment]
### Dmitry said:

We have 3 ways:
1) Using playbin with configuration like in rtspviwer and then we will be able to read current [sample](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-playbin.html#GstPlayBin--sample) from playbin, I think it's better way,
2) trying to debug and understand what happens with jpegenc/pngenc
3) Add gstpad probe, but I think in this case we will have the same like (1) but for getting this we need to make some efforts ..

**Comment by liutingdu** [comment]
@GNUDimarik
I think we need to confirm the performance of playbin first, how fast can it be? I didn't see the latency element there http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-playbin.html

**Comment by GNUDimarik** [comment]
@liutingdu 
There is source element http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-playbin.html#GstPlayBin--source
We can control it like in rtspviewer, I think you remember it, we can use the same callback and set these properties there

**Comment by liutingdu** [comment]
```
static void
need_data_cb (GstElement *playbin, GstElement *rtspsrc, gpointer user_data)
{
  GstRTSPViewerPrivate *priv;
  GstRTSPViewer *viewer = GST_RTSP_VIEWER (user_data);

  GST_DEBUG ("configuring source");

  priv = GST_RTSP_VIEWER_GET_PRIVATE (viewer);

  g_object_set (G_OBJECT (rtspsrc), "user-id", priv->user, NULL);
  g_object_set (G_OBJECT (rtspsrc), "user-pw", priv->pass, NULL);
}
```
Is this what you are talking about?

**Comment by GNUDimarik** [comment]
Yes, we can put other options for source element here too

**Comment by liutingdu** [comment]
I see.. we can add latency here..  Good point!

Then should we just take the rtspviewer code and integrate it with Evercam Play instead of starting from the tutorial code?

**Comment by GNUDimarik** [comment]
Please check license, it license allows us to do it I think yes, it will good start, if no, I think we can do the same without him, but it requires some time

**Comment by GNUDimarik** [comment]
After several tests I can say: playbin convert-sample signal doesn't work, also I tried call function from video interface what implements it, it doesn't work too (under android). So I decided to make second additional pipeline for sample conversion

**Comment by liutingdu** [comment]
@GNUDimarik  When I take a snapshot, it freezes the app for a few seconds(because I see the play/snapshot icons freezing there), is this fixable?

**Comment by GNUDimarik** [comment]
Yes, it's fixable, we need just make it asynchronously. Currently I use this function http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-gstvideo.html#gst-video-convert-sample
But I can switch it to http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-gstvideo.html#gst-video-convert-sample-async
and return shapshot path to java via callback.

**Comment by GNUDimarik** [comment]
Sorry, I use playbin signal "convert-sample", it uses the same API :-) But I can do it manually, Just I wanted to know works it or not because with previous stuff it made just empty green images

**Comment by GNUDimarik** [comment]
I think this issue should be closed to and we need another one something like "Take snapshot from video asynchronously" because we have synchronously implementation for now

**Comment by liutingdu** [comment]
#21  I'll close this card :)
