### ISSUE TITLE
Missing some jars at the libs folder

### ISSUE THREAD

**Issue by SandroMachado** [evercam/evercam-play-android#37]
Some jars are missing from the libs folder, please add them to be possible to build the project.

**Comment by liutingdu** [comment]
@marcoherbst The missing Hikvision jar files are causing Travis build error, I think we need to make a decision in these options:
1. Upload the jars
2. Disable Travis
3. Remove Hikvision local storage

**Comment by marcoherbst** [comment]
If we can find another alternative, then #3 is my choice.

m

On 12 June 2015 at 09:14, Liuting Du <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> The missing Hikvision jar
> files are causing Travis build error, I think we need to make a decision in
> these options:
> 1. Upload the jars
> 2. Disable Travis
> 3. Remove Hikvision local storage
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-play-android/issues/37#issuecomment-111406910>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by SandroMachado** [comment]
Please dont go for the option 2. This will not fix the build problem, only will hide it.

**Comment by marcoherbst** [comment]
I agree +1 @sandromachado and thank you very much for the contribution.

We'll try and clear this decision up today.

Marco

On 12 June 2015 at 22:25, Sandro Machado <notifications@github.com> wrote:

> Please dont go for the option 2. This will not fix the build problem, only
> will hide it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-play-android/issues/37#issuecomment-111622344>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by liutingdu** [comment]
Hikvision dependencies are removed in 48df60737a2ce949497c343804751ff0e9e5ffa9

And I did some further changes in 2bf1145d7e990a6a45078a89c113256fdc08301c for Travis build, now it's passed.

@SandroMachado Thank you again for your kindly help :)
