### ISSUE TITLE
Gstreamer: Add a callback to listen when the video is failed to load. 

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#4]

**Comment by liutingdu** [comment]
### Dmitry said:

We can use for this [gstreamer bus](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/manual/html/chapter-bus.html)

**Comment by GNUDimarik** [comment]
I added VideoActivity::onError(String message, int code) function. C engine calls it when error occurs.
Here is example (I didn't set password):
06-03 23:08:07.907  12225-12570/io.evercam.androidapp E/VideoActivity﹕ error with code 9 and message Could not read from resource.
You can ignore args if you don't need it

**Comment by GNUDimarik** [comment]
Actually it's implemented to, but now it has title VideoActivity::onVideoLoadFailed
