### ISSUE TITLE
Sometimes it shows a black screen when play RTSP camera

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#42]
It only happens randomly, I'll try reproduce it and post the log here.

**Comment by liutingdu** [comment]
@GNUDimarik 

It's happening randomly but frequently. And can be reproduced by following the steps:
1. Quit the app by swiping left
2. Restart the app, when camera list page showing up, click on camera 'O'connell Str' straight away without waiting for snapshot showing up
3. The video page should be playing with the black screen, the logs are:

```
06-22 11:38:22.295  30724-30724/? I/GStreamer﹕ onMeasure called with 320x240
06-22 11:38:22.295  30724-30724/? I/GStreamer﹕ onMeasure called with 320x240
06-22 11:38:22.295  30724-30724/? I/GStreamer﹕ onMeasure called with 320x240
06-22 11:38:22.295  30724-30724/? I/GStreamer﹕ onMeasure called with 320x240
06-22 11:38:22.301    761-16896/? V/WindowManager﹕ Adding window Window{18c8a9df u0 SurfaceView} at 4 of 11 (before Window{3c490f3d u0 io.evercam.androidapp/io.evercam.androidapp.video.VideoActivity})
06-22 11:38:22.311  30724-30724/? D/GStreamer﹕ Surface created: Surface(name=null)/@0x24c58492
06-22 11:38:22.313  30724-30724/? D/GStreamer﹕ Surface changed to format 4 width 1080 height 1701
06-22 11:38:22.313  30724-30724/? I/GStreamer﹕ Media size changed to 1080x1701
06-22 11:38:22.563  30724-30724/? I/GStreamer﹕ onMeasure called with 1080x1701
06-22 11:38:22.563  30724-30724/? I/GStreamer﹕ onMeasure called with 1080x1701
06-22 11:38:22.563  30724-30724/? I/GStreamer﹕ onMeasure called with 1080x1701
06-22 11:38:22.563  30724-30724/? I/GStreamer﹕ onMeasure called with 1080x1701
06-22 11:38:23.277  30724-30861/? D/skia﹕ --- SkImageDecoder::Factory returned null
```

**Comment by liutingdu** [comment]
It's showing black screen but take snapshot is working.

**Comment by liutingdu** [comment]
After adding nativeSurfaceInit() in surfaceChanged(), it seems not happening any more, but since the bug only happens randomly, I'll keep this issue open for more testing.

Thanks @GNUDimarik

**Comment by liutingdu** [comment]
This is fixed by upgrading to the latest GStreamer(1.4.5 - 1.6.1), published with app version 1.6.5

**Comment by GNUDimarik** [comment]
@liutingdu current version uses our own video sink, so I think it's fixed by it.
As you remember we had issue with pause related with video sink

**Comment by liutingdu** [comment]
@GNUDimarik  Yes you fixed the snapshot & pause issue by using our own video sink, but before you changing anything, the random black screen issue was gone after upgrading GStreamer, it just brought other new issues..

**Comment by GNUDimarik** [comment]
@liutingdu yes, but we need to understand if something will wrong cause may be in video sink, because in current release we use this, but no gstreamer's video sink.
So they both fixes this issue, but we use our own.
