### ISSUE TITLE
Record Video

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#47]
Add a record button on the UI, and everytime when user hit the record button, it records the video and write it to a local file (same path with snapshot)

**Comment by GNUDimarik** [comment]
Please provide more details about container and file names. mp4 with h264 I suppose :-)

**Comment by marcoherbst** [comment]
@mosic

Yes, h264 in mp4

M

On 6 July 2015 at 15:26, Dmitry A <notifications@github.com> wrote:

> Please provide more details about container and file names. mp4 with h264
> I suppose :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-play-android/issues/47#issuecomment-118871922>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
