### ISSUE TITLE
Gstreamer: Add a callback to listen when the video successfully loaded

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#5]
Then: 

Show time based on camera timezone when the stream successfully loaded

**Comment by liutingdu** [comment]
### Dmitry said:

Here is several ways
We can use for this [gstreamer bus](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/manual/html/chapter-bus.html) or add pad probe and when there is data and pipeline has no errors we can think video stream is loaded.
But i think bus is faster and easy, but i need to check it, at least we have a message when metadata is loaded ..

**Comment by liutingdu** [comment]
Seems good to me, once the callback is in Java/JNI then I can work on the time text & analytics reports.

Does this require changing to use the Tutorial code?

**Comment by GNUDimarik** [comment]
It's implemented, but I can't show time, Liuting, please do it :-)

**Comment by liutingdu** [comment]
Thanks Dmitry! I'll work on that after your pull request :)

**Comment by GNUDimarik** [comment]
It should be fixed in latest version, please check. Currently you can see time when video starts to playing, I did it via this callback
