### ISSUE TITLE
Zoom on video surface view

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#54]
The video always only resizes when stop zooming, it should zoom smoothly instead - same with zoom on JPG view

**Comment by liutingdu** [comment]
Dmitry said: 

```
[6/18/15, 11:09:54] Dmitry A: it happens because you paint image your self in one case and it does overlay in second
[6/18/15, 11:10:08] Dmitry A: it will work if overlay will contain zommed image
[6/18/15, 11:10:32] Dmitry A: you need to apply zoom to stream data
[6/18/15, 11:16:52] Dmitry A: but here is one question:
[6/18/15, 11:17:17] Dmitry A: how is better? make separate zoom plugin or make it as part of video sink?
```

**Comment by liutingdu** [comment]
@GNUDimarik 

Make separate zoom plugin or make it as part of video, what's the difference? If they both can do what we want, which one is easier?

**Comment by GNUDimarik** [comment]
Difference is if zoom is separate plugin we need make separate bin for zoom and video sink and use it as video sink, but it's more flexible, for example several sinks can play zoomed video.
If zoom is part of video sink, it's more easy to use, but every video sink zoomed video it self via separate zoomer, so it may affects on performance if you show the same stream in different places.

**Comment by liutingdu** [comment]
Why we need to show the same stream in different places?

The other problem is, after zooming in your way, when take snapshot, is it the full image or zoomed/cropped image?

**Comment by GNUDimarik** [comment]
You don't need, it's just example of difference :)
Actually it's fixable: we can do zoom in video sink (zooming as part of video sink) or put sample property to our plugin and get sample from there before zooming.
But IMHO when user tries to get snapshot he should get the same like he see, for example user zoomed some face on video and wants to save the face like photo

**Comment by liutingdu** [comment]
About parameters - the one you mentioned```int top, int bottom, int left, int right``` is enough! But will need more thinking about how to fit it in my existing code,  see method onActionZoom() in OnSwipeTouchListener

Snapshot - I think full image is enough, they can crop it by themselves if they want! Does it requires more work to make it full image?

**Comment by GNUDimarik** [comment]
2015-06-18 19:10 GMT+03:00 Liuting Du <notifications@github.com>:

> About parameters - the one you mentionedint top, int bottom, int left,
> int right is enough! But will need more thinking about how to fit it in
> my existing code, see method onActionZoom() in OnSwipeTouchListener
>
I'll review your code and update you today

> Snapshot - I think full image is enough, they can crop it by themselves if
> they want! Does it requires more work to make it full image?
>
No, it doesn't

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-play-android/issues/54#issuecomment-113204735>
> .
>



-- 
Regards,
Dmitry

**Comment by liutingdu** [comment]
@GNUDimarik 

Now in my code it's just resizing surface view by changing margins, the code is easy to understand, let me know if you have questions!

Then let's just do full image!

**Comment by GNUDimarik** [comment]
Where can I review the code?
I can't find onActionZoom() in current repo

**Comment by liutingdu** [comment]
It's in branch - zooming: https://github.com/evercam/evercam-play-android/blob/zooming/evercamPlay/src/main/java/io/evercam/androidapp/video/OnSwipeTouchListener.java

**Comment by GNUDimarik** [comment]
I think we need to add zoom factor property to zoom plugin. So you will put
factor, top, bottom, left and right to plugin and it shold work
19 июня 2015 г. 10:37 пользователь "Liuting Du" <notifications@github.com>
написал:

**Comment by liutingdu** [comment]
@GNUDimarik 

As you can see from the code, I am resizing the whole surface view (not only the video size) by setting it's margin. I am not sure what your top, bottom left and right values are? We need to discuss it after you test it on Android :)

**Comment by GNUDimarik** [comment]
You should not to do it, please remember: not you paint video, it does gstreamer x overlay interface.
Please do nothing with surface when you use gstreamer playing, no jpeg because in this case gstreamer will perform zooming.

**Comment by liutingdu** [comment]
Seems this is the same problem: http://stackoverflow.com/questions/20491499/resizing-surface-view-for-aspect-ratio-change-in-video-display-in-android#comment30627791_20491603

**Comment by GNUDimarik** [comment]
Currently I decode video frames to ARGB (RGBA, arm uses little endian) and paint it on ImageView as bitmap via appsink. But current implementation is really slowly, I'll try to optimize it, may be via skia bitmap, I'm not sure yet, I need to investigate it

**Comment by liutingdu** [comment]
I've added basic pinch zoom based on ExoPlayer, closing this. Will create new tickets for further issues.
