### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#58]
Seems our GStreamer player doesn't play audio from the camera, @GNUDimarik  can you confirm this?

**Comment by GNUDimarik** [comment]
I didn't head it, but playbin should support it automatically. Please add camera with sound to my account for testing

**Comment by liutingdu** [comment]
@GNUDimarik 

Just shared you the camera with audio, the camera name is 'Merrion Square'

VLC is able to load the stream with audio.

But the player couldn't load the video from this camera at all, the behaviour is similar with #42

**Comment by marcoherbst** [comment]
Dima / LD,

I would not be surprised if you might have hit on something that is a much
harder problem than it may at first seem.

If it is ... then it's ok to set this aside as a bigger issue for the
future.

M

On 26 June 2015 at 12:13, Liuting Du <notifications@github.com> wrote:

> @GNUDimarik <https://github.com/GNUDimarik>
>
> Just shared you the camera with audio, the camera name is 'Merrion Square'
>
> VLC is able to load the stream with audio.
>
> But the player couldn't load the video from this camera at all, the
> behaviour is similar with #42
> <https://github.com/evercam/evercam-play-android/issues/42>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-play-android/issues/58#issuecomment-115649621>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by GNUDimarik** [comment]
Did you try to play this stream via VLC player or some other stuff?

**Comment by liutingdu** [comment]
@GNUDimarik Yes, VLC is able to play it with both video and audio

**Comment by liutingdu** [comment]
The stream loading problem is nothing to do with audio, it's about mpeg4 decoder doesn't work on gstreamer, I'll create a new issue for it - #59

Audio need to be tested on more cameras.

**Comment by liutingdu** [comment]
Audio works for the 'Carrolls Packing Camera', which means playbin does support audio by default.. I'll close this issue.
