### ISSUE TITLE
onVideoLoaded() is called but showing black screen

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#59]
This issue was found while testing the Merrion Square camera for audio #58 

@GNUDimarik confirmed that it's caused by mpeg4 decoder doesn't work on gstreamer

**Comment by liutingdu** [comment]
Now this issue can be reproduced by playing the 'Office' camera.

It's different from the other blank screen problem #42 

This is happening 100% and take snapshot doesn't work.

**Comment by liutingdu** [comment]
@GNUDimarik This is happening for both the old code and the new code

**Comment by liutingdu** [comment]
gst-launch-1.0 rtspsrc protocols=4 location=rtsp://hikvis-7uy.evr.cm:554/h264/ch1/main/av_stream user-id=admin user-pw=12345 latency=0 ! decodebin ! videoconvert ! autovideosink 

It plays video from command line with warnings: 

```
WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstGLImageSink:autovideosink0-actual-sink-glimage: A lot of buffers are being dropped.
Additional debug info:
gstbasesink.c(2794): gboolean gst_base_sink_is_too_late(GstBaseSink *, GstMiniObject *, GstClockTime, GstClockTime, GstClockReturn, GstClockTimeDiff, gboolean) (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstGLImageSink:autovideosink0-actual-sink-glimage:
There may be a timestamping problem, or this computer is too slow.
```

It's the camera that has black screen in E-Play Android

**Comment by GNUDimarik** [comment]
I hope it's fixed by video sink, please test it
