### ISSUE TITLE
Don't ask for camera ID when adding camera

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#62]
Two possible approaches

1. Don't show camera ID fields at all
2. Show it but auto populate an random ID

**Comment by marcoherbst** [comment]
dont show it at all.
m

On 1 July 2015 at 16:59, Liuting Du <notifications@github.com> wrote:

> Two possible approaches
>
>    1. Don't show camera ID fields at all
>    2. Show it but auto populate an random ID
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-play-android/issues/62>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
