### ISSUE TITLE
Re-stream from Evercam server (using HLS)

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#63]
Tried to play the re-streamed RTMP stream with GStreamer, it's able to play it after adding the GStreamer 'rtmp' plugin. 

But the [rtmp plugin](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-bad-plugins/html/gst-plugins-bad-plugins-rtmpsrc.html) doesn't support changing buffer time / latency / protocol, I didn't see a way to reduce the stream loading time, currently it takes about 10 secs to load. ([rtspsrc](http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-rtspsrc.html) is what we are currently using, it's one of the good plugins, load the stream in 1-2 seconds)

**Comment by GNUDimarik** [comment]
We can implement with reading rtmp frames via ffmpeg and put them in pipeline via appsrc

**Comment by marcoherbst** [comment]
Probably the best thing to do here is to wait until we get an RTSP endpoint from media.evercam.io

**Comment by liutingdu** [comment]
https://github.com/evercam/evercam-play-android/issues/144
