### ISSUE TITLE
Implement Sharing natively

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#72]
- [x] Public & Discoverable 
- [x] List users that has access to the camera 
- [x] Remove/invoke sharing 
- [x] Transfer owner 
- [x] Edit existing sharing 
- [x] Create a new share

Some improvements on dashboard should be done before this. (Currently we display on the minimum info about a sharee (username) ... Extend that to FirstName  LastName, Email and more)

**Comment by marcoherbst** [comment]
:bow:
