### ISSUE TITLE
Add PTZ functionality

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-play-android#95]
Available on media.evercam.io 

get "/v1/cameras/:id/ptz/status"
get "/v1/cameras/:id/ptz/presets"
post "/v1/cameras/:id/ptz/home"
post "/v1/cameras/:id/ptz/home/set"
post "/v1/cameras/:id/ptz/presets/:preset_token"
post "/v1/cameras/:id/ptz/presets/create/:preset_name"
post "/v1/cameras/:id/ptz/presets/go/:preset_token"
post "/v1/cameras/:id/ptz/continuous/start/:direction"
post "/v1/cameras/:id/ptz/continuous/zoom/:mode"
post "/v1/cameras/:id/ptz/continuous/stop"
post "/v1/cameras/:id/ptz/relative?left=10&zoom=2"
get "/v1/cameras/:id/macaddr"

M

**Comment by liutingdu** [comment]
Is there any documents around the API endpoints?

**Comment by liutingdu** [comment]
The PTZ  functionalities have been merged to master and published with version 1.5.3.
