### ISSUE TITLE
Make zoom and download image work for recordings

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#96]

**Comment by liutingdu** [comment]
Zoom is done in 68246103047ca61dd227b9b1058d11984fb7620e

Download image is waiting for a bug fix from recording widget: https://github.com/evercam/evercam-dashboard/issues/655

**Comment by liutingdu** [comment]
After the bug fix https://github.com/evercam/evercam-dashboard/issues/655, the save image button still doesn't work in the recording webview. But it works in Chrome. 

By looking at the [code for saving image](https://github.com/evercam/evercam-dashboard/blob/510f595ea92bb24a4b53b114e224edad3ad288e6/app/assets/javascripts/saveimage.js), it's using the 'download' attribute, and according to [this issue](https://code.google.com/p/chromium/issues/detail?id=432414), the Android Chromium browser does not support the 'download' attribute.

@azharmalik3 @marcoherbst @mosic Is there any other approaches to save image that could support Chromium? Please let me know if you have any other ideas around this.

**Comment by mosic** [comment]
@liutingdu Is there another way to save an image using JavaScript in Android WebView? If yes, we could use that conditionally just in the app?

**Comment by liutingdu** [comment]
@mosic 

I don't know if there are any. It seems the 'download' attribute comes with HTML5, and it doesn't work for Safari as well (I tested it on my Mac) http://www.w3schools.com/tags/att_a_download.asp

If we both don't have a better idea of using a different approach on the web, I could handle it on Android by adding a download listener, something like this: http://stackoverflow.com/questions/26379174/download-images-using-android-webview

**Comment by mosic** [comment]
@liutingdu Handling it separately in Android app sounds sensible, as the regular download does work in mobile Chrome (just tried it).

**Comment by liutingdu** [comment]
Tried to handle it in Android but it only works for valid URLs that conform to [RFC 3986](http://tools.ietf.org/html/rfc3986#appendix-A). ```http://.../image.jpg``` works. And what we have is the base64 data ```data:image/jpeg;base64, ...```

Posted [a question on StackOverflow](http://stackoverflow.com/questions/33105304/android-webview-shouldoverrideurlloading-is-not-called-for-base64-image-data-u) but haven't got any reply yet.

@mosic  Let me know if you have any ideas :)

**Comment by liutingdu** [comment]
Got a valid answer: http://stackoverflow.com/questions/33105304/android-webview-shouldoverrideurlloading-is-not-called-for-base64-image-data-u

It's the 'download' attribute prevents the client retrieving the base64 data URL. The solution is to remove the 'download' attribute for Android app client, I have investigated how to validate if it's from the Android app or not in https://github.com/evercam/evercam-dashboard/issues/622. 

Basically it requires 
1. I append an additional string to the user agent in Android WebView and 
2. In [recordings JavaScript](https://github.com/evercam/evercam-dashboard/blob/510f595ea92bb24a4b53b114e224edad3ad288e6/app/assets/javascripts/saveimage.js), remove the 'download' attribute if the user agent contains the the string I appended. 

@mosic What do you think? Let me know if it make sense then I'll create an issue for it in evercam-dashboard.

**Comment by mosic** [comment]
@liutingdu That sounds good. It's a simple solution but should work for both desktop and mobile browsers and the Android app.

**Comment by liutingdu** [comment]
I've done my part in https://github.com/evercam/evercam-play-android/commit/457381dd5b0e60293d810085f6482c86aefd21f0 and created an issue in dashboard: https://github.com/evercam/evercam-dashboard/issues/727

**Comment by liutingdu** [comment]
There is a small issue https://github.com/evercam/evercam-dashboard/issues/840
