### ISSUE TITLE
Make the setting 'Show offline cameras' to be true by default

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#97]
Otherwise when new account is created and the demo camera is offline, it shows nothing in camera list

**Comment by marcoherbst** [comment]
Good thinking. Could you add a similar ticket to iOS and Dashboard please.
M

On 14 September 2015 at 14:39, Liuting Du <notifications@github.com> wrote:

> Otherwise when new account is created and the demo camera is offline, it
> shows nothing in camera list
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-play-android/issues/97>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by liutingdu** [comment]
Dashboard is showing the offline cameras by default.

I'll create one for the iOS app
